# Generated by Django 5.0.2 on 2024-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='not started', max_length=12),
        ),
    ]
